# Generated by Django 2.1.7 on 2019-03-28 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='descripcion',
            field=models.TextField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='origen',
            name='provincia',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
