# Generated by Django 2.1.7 on 2019-03-26 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=255, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('anio', models.IntegerField()),
                ('obs', models.CharField(blank=True, max_length=30, null=True)),
                ('ruta', models.ImageField(upload_to='static/images/fotos')),
            ],
        ),
        migrations.CreateModel(
            name='FotoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fotos.Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tipofoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('serie', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotos.Procedencia'),
        ),
        migrations.AddField(
            model_name='foto',
            name='tipofoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotos.Tipofoto'),
        ),
    ]
