# Generated by Django 2.1.7 on 2019-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='procedencia',
            name='nombre',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tipofoto',
            name='nombre',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tipofoto',
            name='serie',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
