# Generated by Django 2.1.7 on 2019-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='procedencia',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Procedencia',
        ),
    ]
