# Generated by Django 2.1.7 on 2019-03-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_auto_20190306_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='foto',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotos.Procedencia'),
        ),
    ]
