# Generated by Django 2.1.7 on 2019-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0005_fotoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='ruta',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
